{{- if .Values.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ren3.fullname" . }}
  labels:
{{ include "ren3.labels" . | indent 4 }}
data: {{ include "ren3.secretData" . }}
{{- end }}