apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ren3.serviceAccountName" . }}
  labels:
    {{- include "ren3.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false