apiVersion: v1
kind: Service
metadata:
  name: {{ include "ren3.fullname" . }}-web
  labels:
    {{- include "ren3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    {{- range .Values.web.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "ren3.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
