{{- if .Values.vault.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-ren3-ingestor-env
  labels:
    {{- include "ren3.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestor
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: vault-ren3-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.vault.externalSecret.ingestor.target.nameEnv }}
    template:
      engineVersion: v2
      # Define the data structure of the target Kubernetes Secret
      data:
        # Create a single key named '.env' in the K8s Secret
        # Its value will be the formatted string of all secrets
        .env: |
          {{ printf "{{- range $key, $value := . }}" }}
          {{ printf "{{ $key }}={{ $value }}" }}
          {{ printf "{{- end }}" }}
  dataFrom:
    - extract:
        key: {{ .Values.vault.externalSecret.ingestor.target.dataFromKeyEnv }}
{{- end }}