{{- if .Values.vault.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-ren3-ingestor-config
  labels:
    {{- include "ren3.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestor
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: vault-ren3-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.vault.externalSecret.ingestor.target.nameConfig }}
  data:
  - secretKey: config.json
    remoteRef:
      key: {{ .Values.vault.externalSecret.ingestor.target.dataFromKeyConfig }}
      property: config
{{- end }}