{{- if .Values.vault.enabled -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-ren3-secret-store
  labels:
    {{- include "ren3.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      {{- with .Values.vault.clusterSecretStore }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}